apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cicd-demo #cluster name
  region: us-west-2 #desired region

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 3
    ssh:
      allow: false

